# Generated by Django 6.0 on 2025-12-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='line_total_cop',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad x precio unitario.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_cop',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, se usa el precio del plato.', null=True),
        ),
    ]
