# Generated by Django 6.0 on 2025-12-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orderitem_line_total_cop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='line_total_cop',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price_cop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
